spring.application.name=demo
firebase.config.path=classpath:firebaseAdminSdk.json

# Server Port
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://ep-bitter-dew-aoy89cil-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rp0hOkBuvy3M
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect